### ISSUE TITLE
Compare and merge jack2 example-clients and tools

### ISSUE THREAD

**Issue by dvzrv** [jackaudio/jack-example-tools#9]
Some [example-clients](https://github.com/jackaudio/jack2/tree/0727bbc386288f6ff5cb6876d2321836d562221e/example-clients) and [tools](https://github.com/jackaudio/jack2/tree/0727bbc386288f6ff5cb6876d2321836d562221e/tools) in jack2 have diverted slightly from the ones in the dedicated repositories (and thus also from here) and new ones have been added.

The below list is a checklist of files that need to be consolidated. All files that have only seen non-functional changes (e.g. indentation, non code changes) are ignored:

- [x] example-clients/capture_client.c <--> jack2/example-clients/capture_client.c #12 
- [x] example-clients/impulse_grabber.c <--> jack2/example-clients/impulse_grabber.c #13
- [x] example-clients/inprocess.c <--> jack2/example-clients/inprocess.c #36 
- [x] example-clients/latent_client.c <--> jack2/example-clients/latent_client.c #14
- [x] example-clients/metro.c <--> jack2/example-clients/metro.c #15
- [x] example-clients/midiseq.c <--> jack2/example-clients/midiseq.c #16
- [x] example-clients/midisine.c <--> jack2/example-clients/midisine.c #17
- [x] example-clients/showtime.c <--> jack2/example-clients/showtime.c #18
- [x] example-clients/simple_client.c <--> jack2/example-clients/simple_client.c #19 
- [x] tools/alsa_in.c <--> jack2/tools/alsa_in.c #20 
- [x] tools/alsa_out.c <--> jack2/tools/alsa_out.c #21
- [x] tools/connect.c <--> jack2/tools/connect.c #22
- [x] tools/evmon.c <--> jack2/tools/evmon.c #23
- [x] tools/freewheel.c <--> jack2/tools/freewheel.c #24
- [x] tools/iodelay.c <--> jack2/tests/iodelay.cpp #25
- [x] tools/ipload.c <--> jack2/tools/ipload.c #26
- [x] tools/ipunload.c <--> jack2/tools/ipunload.c #27
- [x] tools/midi_dump.c <--> jack2/tools/midi_dump.c #28
- [x] tools/monitor_client.c <--> jack2/tools/monitor_client.c #29
- [x] tools/netsource.c <--> jack2/tools/netsource.c #37 
- [x] tools/property.c <--> jack2/tools/property.c #30
- [x] tools/samplerate.c <--> jack2/tools/samplerate.c #31
- [x] tools/session_notify.c <--> jack2/tools/session_notify.c #32
- [x] tools/transport.c <--> jack2/tools/transport.c #33
- [x] tools/tw.c <--> jack2/tools/tw.c #34
- [x] tools/wait.c <--> jack2/tools/wait.c #35

A few more [test executables](https://github.com/jackaudio/jack2/tree/0fe68adecccd5a2884ed9c955d1c58e6566546ba/tests) are always built alongside jack2 (iodelay.c is actually from the tools repository) and should be merged into this repository as well.

**Comment by dvzrv** [comment]
With #10 we now have "feature parity", but not "behavioral parity" with jack2 (unless something has been forgotten).

The executables and libraries now need to be compared.

**Comment by dvzrv** [comment]
@falkTX FYI my process for comparing these things is roughly:

```
git clone git@github.com:jackaudio/jack2.git
git-filter-repo --path <path/to/file> --prune-empty always
```

```
git clone git@github.com:jackaudio/jack-example-tools.git
git checkout <feature_branch>
git remote add jack2 <dir_to_jack2_clone>
git fetch jack2
```

Then I look around for in which commit the file has been introduced in the jack2 repo and attempt a diff in the jack-example-tools repo:

```
git diff <checksum> <path_to_file>
```

If I found a matching commit (empty diff), then I was able to apply the commits from the jack2 repo via cherry-pick.
If there was no matching commit, I nuked the original version and merged the file over from the jack2 remote.

**Comment by dvzrv** [comment]
All jack2 related changes have been applied and this ticket can be closed.
